### ISSUE TITLE
Crash on loading the world

### ISSUE THREAD

**Issue by MatthiasMann** [yrsegal/NaturalPledge#18]
Just updated to Botania 340 and NaturalPledge 1.9 and got this:
java.lang.NullPointerException: Ticking player
    at shadowfox.botanicaladdons.common.items.travel.stones.ItemPolyStone$Companion.onPlayerTick(ItemPolyStone.kt:54)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_352_Companion_onPlayerTick_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:493)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1931)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

Full server crash log:
http://pastebin.com/LCNLHVua

**Comment by yrsegal** [comment]
oops.

**Comment by yrsegal** [comment]
curseforge build coming soon
