### ISSUE TITLE
Console spam on player login

### ISSUE THREAD

**Issue by LemADEC** [yrsegal/NaturalPledge#25]
As of NaturalPledge-r1.10 + Botania r1.9-340, console gets spammed when a player logs in the first time. Issue seems intermittent.

```
[16:51:56] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
java.lang.RuntimeException: DISPATCHER expects a NetworkDispatcher
>       at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$2.validateArgs(FMLOutboundHandler.java:81) ~[FMLOutboundHandler$OutboundTarget$2.class:?]
>       at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:282) ~[FMLOutboundHandler.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) ~[MessageToMessageEncoder.class:?]
>       at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
>       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
>       at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:240) [SimpleNetworkWrapper.class:?]
>       at shadowfox.botanicaladdons.common.items.travel.stones.ItemWaystone$Companion.onWorldTick(ItemWaystone.kt:72) [ItemWaystone$Companion.class:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_444_Companion_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) [EventBus.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
>       at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269) [FMLCommonHandler.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by yrsegal** [comment]
Can't reproduce
